# Generated by Django 2.2.2 on 2019-06-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
