# Generated by Django 2.2.2 on 2019-06-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
