# Generated by Django 2.2.2 on 2019-06-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0004_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=250)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
